#Test with: http://editor.swagger.io/


swagger: '2.0'
info:
  version: 1.0.0
  title: Microservice for sessions manage
  description: Java Srpring boot + MySQL 
  license:
    name: Software Architecture, 2020-I
host: host:4000 
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/java/code-analysis:
    post:
      summary: Analyses java code
      parameters:
        - name: schedule
          in: body
          required: true
          description: response
          schema:
            $ref: '#/definitions/ScheduleInput'
      responses:
        '200':
          description: Analyzed
          schema:
            $ref: '#/definitions/styleErrorArray'

  

definitions:  
  
  styleErrorArray:
    type: array
    items:
      type: object
      $ref: '#/definitions/styleError'
      
  styleError:
    type: object
    properties:
      errorMessage:
        type: string
      line:
        type: integer
      column:
        type: integer
      suggestion:
        type: string
      hasCorrection:
        type: boolean
      previousCode:
        type: string
      correctedCode:
        type: string
  
  ScheduleInput:
    type: object
    properties:
      complexity:
        type: integer
      maxNameLength:
        type: integer
      maxLineCountByFunction:
        type: integer
      maxCommentedLinesCount:
        type: integer
      minCommentedLinesCount:
        type: integer
      maxClassesByFile:
        type: integer
      maxFunctionCountByClass:
        type: integer
      text:
        type: string
